runtime: go120  # or another supported version

instance_class: F2

env_variables:
  SERVER_ADDRESS: ":8080"
  SECRET_PATH: "lan-site-94255-b56432cf737d.json"
  SCOPE: "https://www.googleapis.com/auth/spreadsheets"
  EVENT_SPREADSHEET_ID: "1zssMHkizrIetXEMkV3Qo-wj6QBiv9jf3A2S-g5IaoE0"
  EVENT_READ_RANGE: "master!2:1000"
  ENTRIES_SPREADSHEET_ID: "1IglEBmeCFs9FwL0bQ1vh93b-wJp6KTWurRX2sxcsd3A"